### ISSUE TITLE
Rectangular spotlight?

### ISSUE THREAD

**Issue by JMSerruya** [lekshmiraveendranath/Spotlight#11]
Any way to create a rectangular spotlight?, the Oval deforms quite a bit if i want to highlight a bigger rectangle.

**Comment by lekshmiraveendranath** [comment]
Sure. You can pass the target as type .rect
See example below
```SpotlightNode(text: "Show Spotlight over a rectangle", target: .rect(redView.bounds))]```

**Comment by JMSerruya** [comment]
Thanks !

**Comment by JMSerruya** [comment]
@lekshmiraveendranath Even passing a rect, the highlight is still an oval, what i'm asking if it there's a way to make the highlight itself rectangular, given that it deforms quite a bit if i'm hightlighting a big rectangle.
