### ISSUE TITLE
Changing button title for localized description

### ISSUE THREAD

**Issue by ElyDantas** [lekshmiraveendranath/Spotlight#3]
I'd like to have access to 'back' and 'next' buttons so i can provide translations.

**Comment by lekshmiraveendranath** [comment]
Added properties in Spotlight to expose titles for the buttons. Added in release 1.6.0

https://github.com/lekshmiraveendranath/Spotlight/releases/tag/1.6.0

**Comment by ElyDantas** [comment]
Hi, thanks for the `.backButtonTitle` and `.nextButtonTitle` property access but i'm having a line breaking problem, it's truncating the middle of word, since back/next button are bellow node's text, could it be expanded? Maybe back and next buttons could be in horizontal equal spacing distribution stack with 16 of spacing or something to prevent clipping?

![IMG_1994](https://user-images.githubusercontent.com/12100371/109450618-17b6c080-7a2a-11eb-8648-822531981e8d.jpg)
