### ISSUE TITLE
Adding only one node still appears "Back" and "Next" options

### ISSUE THREAD

**Issue by ElyDantas** [lekshmiraveendranath/Spotlight#4]
Adding only one node still appears "Back" and "Next" options. If node is last one, label should change it's title to finish or something, same thing for the first node, there should not have a "back" button.

**Comment by lekshmiraveendranath** [comment]
This was fixed in https://github.com/lekshmiraveendranath/Spotlight/releases/tag/1.6.0
Back and Next buttons are hidden if they are not available as the next action
