### ISSUE TITLE
Is there any option to dismiss all the walkthrough?

### ISSUE THREAD

**Issue by NandoxD** [lekshmiraveendranath/Spotlight#9]
Is there any option to dismiss all the walkthrough?

**Comment by lekshmiraveendranath** [comment]
There is a 'X' button on the top right corner on the text box, which dismisses the whole walkthrough
![Close](https://user-images.githubusercontent.com/14341293/61685492-c5e87900-acd1-11e9-8fcf-1f7cd9a4c03a.png)
